// Taxonomía de técnicas según la especificación de diseño
export const CATEGORIAS = [
  { id: 'depie', nombre: 'De pie', sub: 'Stójka · wrestling · judo' },
  { id: 'pases', nombre: 'Pases', sub: 'Gi · No-Gi · defensa de leg locks' },
  { id: 'guardia', nombre: 'Guardia', sub: 'Cerrada · lasso · butterfly' },
  { id: 'bottom', nombre: 'Bottom work', sub: 'Połówka · Z guard · DLR · single X' },
  { id: 'leglocks', nombre: 'Leg locks', sub: 'Ataque y defensa · ⚠ por nivel', ancha: true },
]

export const TECNICAS = [
  // De pie — Wrestling
  { id: 'duckunder', nombre: 'Duck under', cat: 'depie', familia: 'Wrestling', mecanica: 'Espalda',
    pasos: ['Controla el brazo y la nuca con agarre 2-sobre-1.', 'Baja el nivel flexionando las rodillas, no la espalda.', 'Pasa la cabeza bajo la axila del rival.', 'Emerge detrás con el pecho pegado a su espalda.'],
    encadena: ['singleleg', 'backtake'], contras: [], prereq: ['Postura básica'] },
  { id: 'armdrag', nombre: 'Arm drag', cat: 'depie', familia: 'Wrestling', mecanica: 'Brazo',
    pasos: ['Agarra la muñeca del rival con tu mano cruzada.', 'Con la otra mano toma su tríceps.', 'Jala en diagonal pasando su brazo frente a tu pecho.', 'Da un paso al ángulo y busca la espalda.'],
    encadena: ['backtake', 'singleleg'], contras: [], prereq: [] },
  { id: 'singleleg', nombre: 'Single leg', cat: 'depie', familia: 'Wrestling', mecanica: 'Pierna',
    pasos: ['Baja el nivel con cambio de altura.', 'Penetra con el pie dominante entre sus piernas.', 'Captura la pierna con ambos brazos, oreja pegada.', 'Levanta y corre la esquina para derribar.'],
    encadena: ['doublelegsmash'], contras: ['uchimata'], prereq: ['Cambio de nivel'] },
  { id: 'backtake', nombre: 'Back take (de pie)', cat: 'depie', familia: 'Wrestling', mecanica: 'Espalda',
    pasos: ['Desde el duck under o arm drag, ajusta el candado de manos.', 'Pega la cadera a su glúteo.', 'Derriba con mat return o sube los ganchos.'],
    encadena: [], contras: [], prereq: ['duckunder'] },
  { id: 'slideby', nombre: 'Slide by', cat: 'depie', familia: 'Wrestling', mecanica: 'Espalda',
    pasos: ['Desde el agarre de nuca, empuja y suelta.', 'Cuando el rival reacciona hacia ti, desliza al costado.', 'Emerge en su espalda.'],
    encadena: ['backtake'], contras: [], prereq: [] },
  // De pie — Judo
  { id: 'taiotoshi', nombre: 'Tai otoshi', cat: 'depie', familia: 'Judo', mecanica: 'Pierna',
    pasos: ['Rompe la postura hacia su esquina delantera.', 'Gira entrando con pivote de ambos pies.', 'Extiende tu pierna bloqueando su tobillo.', 'Proyecta girando el torso.'],
    encadena: ['uchimata'], contras: [], prereq: ['Kuzushi'] },
  { id: 'sasae', nombre: 'Sasae tsurikomi ashi', cat: 'depie', familia: 'Judo', mecanica: 'Pierna',
    pasos: ['Eleva con el agarre de solapa (tsurikomi).', 'Bloquea su tobillo adelantado con tu planta.', 'Gira el volante de los agarres para proyectar.'],
    encadena: ['taiotoshi'], contras: [], prereq: ['Kuzushi'] },
  { id: 'haraigoshi', nombre: 'Harai goshi', cat: 'depie', familia: 'Judo', mecanica: 'Cadera',
    pasos: ['Entra con la cadera cruzando su línea.', 'Carga su peso sobre tu cadera.', 'Barre con la pierna extendida su muslo.'],
    encadena: ['uchimata'], contras: [], prereq: ['O goshi'] },
  { id: 'uchimata', nombre: 'Uchimata', cat: 'depie', familia: 'Judo', mecanica: 'Cadera',
    pasos: ['Rompe la postura con el agarre de solapa y manga.', 'Gira la cadera dentro del espacio entre ambos.', 'Eleva con la pierna interior entre sus muslos.', 'Proyecta continuando la rotación del torso.', 'Controla la caída para aterrizar en side control.'],
    encadena: ['singleleg', 'sasae'], contras: ['Uchimata sukashi'], prereq: ['Agarre básico Gi', 'Kuzushi'] },
  { id: 'ogoshi', nombre: 'Rzut przez biodro (O goshi)', cat: 'depie', familia: 'Judo', mecanica: 'Cadera',
    pasos: ['Entra girando con el brazo rodeando su cintura.', 'Baja tu cadera bajo la suya.', 'Carga y proyecta por encima de la cadera.'],
    encadena: ['haraigoshi'], contras: [], prereq: [] },
  { id: 'kataguruma', nombre: 'Kata guruma', cat: 'depie', familia: 'Judo', mecanica: 'Hombro',
    pasos: ['Baja el nivel bajo su brazo.', 'Carga su cuerpo sobre tus hombros.', 'Proyecta rodando el "molino".'],
    encadena: [], contras: [], prereq: ['Cambio de nivel'] },
  // Pases
  { id: 'torreando', nombre: 'Pase torreando', cat: 'pases', familia: 'No-Gi', mecanica: 'Presión',
    pasos: ['Controla ambas rodillas con agarre de pantalón o espinillas.', 'Lanza sus piernas a un lado como capote de torero.', 'Corre al costado y ancla el hombro en su pecho.'],
    encadena: ['sidecontrol'], contras: ['Retención DLR'], prereq: ['Postura en guardia abierta'] },
  { id: 'pasegi', nombre: 'Pase de rodilla (Gi)', cat: 'pases', familia: 'Gi', mecanica: 'Presión',
    pasos: ['Agarre de solapa y pantalón.', 'Corta con la rodilla en diagonal sobre su muslo.', 'Ventana de hombro y transición a side control.'],
    encadena: ['sidecontrol'], contras: [], prereq: [] },
  { id: 'defensaleglockpase', nombre: 'Defensa de leg locks en el pase', cat: 'pases', familia: 'No-Gi', mecanica: 'Defensa',
    pasos: ['Mantén los pies fuera del alcance de sus caderas.', 'Si entra al single X, extrae la rodilla primero.', 'Recupera postura y ángulo antes de seguir el pase.'],
    encadena: ['torreando'], contras: [], prereq: [] },
  // Guardia
  { id: 'scissorsweep', nombre: 'Scissor sweep', cat: 'guardia', familia: 'Cerrada', mecanica: 'Raspado',
    pasos: ['Agarre de solapa cruzada y manga.', 'Abre la guardia y monta la espinilla en su cadera.', 'Tijeretea las piernas mientras jalas los agarres.', 'Sigue el impulso hasta la montada.'],
    encadena: ['triangle'], contras: [], prereq: ['Guardia cerrada'] },
  { id: 'triangle', nombre: 'Triangle', cat: 'guardia', familia: 'Cerrada', mecanica: 'Estrangulación',
    pasos: ['Controla una muñeca y empuja el otro brazo dentro.', 'Sube la cadera y cierra el candado sobre su cuello.', 'Ajusta el ángulo jalando tu espinilla.', 'Cierra la figura cuatro y aprieta con las piernas.'],
    encadena: ['omoplata', 'armbar'], contras: ['Postura y stack'], prereq: ['Guardia cerrada', 'Control de postura'] },
  { id: 'omoplata', nombre: 'Omoplata', cat: 'guardia', familia: 'Cerrada', mecanica: 'Hombro',
    pasos: ['Desde el triángulo fallido, gira la cadera hacia fuera.', 'Pasa la pierna sobre su hombro.', 'Siéntate y controla su cadera para finalizar.'],
    encadena: ['triangle'], contras: ['Rolido frontal'], prereq: ['triangle'] },
  { id: 'armbar', nombre: 'Armbar', cat: 'guardia', familia: 'Cerrada', mecanica: 'Palanca',
    pasos: ['Aísla el brazo con control de muñeca y codo.', 'Sube la cadera y gira perpendicular.', 'Pasa la pierna sobre su cara.', 'Extiende la cadera para finalizar.'],
    encadena: ['triangle'], contras: ['Hitchhiker escape'], prereq: ['Guardia cerrada'] },
  { id: 'lasso', nombre: 'Guardia lasso', cat: 'guardia', familia: 'Lasso', mecanica: 'Control',
    pasos: ['Agarre de manga profunda.', 'Enrosca tu pierna por fuera de su brazo.', 'Combina con DLR o araña para desequilibrar.'],
    encadena: ['barratoplata'], contras: [], prereq: [] },
  { id: 'lapela', nombre: 'Control de lapela', cat: 'guardia', familia: 'Lasso', mecanica: 'Control',
    pasos: ['Saca la solapa de su cinturón.', 'Pásala por detrás de su pierna o brazo.', 'Usa la solapa como tercer brazo para barrer o atacar.'],
    encadena: ['barratoplata'], contras: [], prereq: [] },
  { id: 'barratoplata', nombre: 'Barrato plata', cat: 'guardia', familia: 'Lasso', mecanica: 'Espalda',
    pasos: ['Desde lasso + solapa, invierte bajo su base.', 'Gira como berimbolo usando la solapa como polea.', 'Emerge en la espalda con los ganchos.'],
    encadena: [], contras: [], prereq: ['lasso', 'lapela'] },
  { id: 'butterfly', nombre: 'Guardia butterfly', cat: 'guardia', familia: 'Butterfly', mecanica: 'Control',
    pasos: ['Siéntate con ambos ganchos de empeine dentro de sus muslos.', 'Controla brazo y nuca o doble solapa.', 'Genera elevación con los ganchos para barrer.'],
    encadena: ['wrestleup', 'doublelegsmash'], contras: [], prereq: [] },
  { id: 'wrestleup', nombre: 'Wrestle up', cat: 'guardia', familia: 'Butterfly', mecanica: 'Pierna',
    pasos: ['Desde butterfly, captura su pierna adelantada.', 'Ponte de pie manteniendo el control del single.', 'Termina como single leg de pie.'],
    encadena: ['singleleg'], contras: [], prereq: ['butterfly'] },
  { id: 'doublelegsmash', nombre: 'Double leg smash', cat: 'guardia', familia: 'Butterfly', mecanica: 'Presión',
    pasos: ['Desde butterfly, ata ambas piernas.', 'Conduce con el hombro aplastando hacia el tatami.', 'Consolida en side control pesado.'],
    encadena: ['sidecontrol'], contras: [], prereq: ['butterfly'] },
  // Bottom work
  { id: 'polowka', nombre: 'Połówka (media guardia)', cat: 'bottom', familia: 'Media guardia', mecanica: 'Control',
    pasos: ['Atrapa una de sus piernas entre las tuyas.', 'Pelea el underhook con el brazo interior.', 'Trabaja hacia dogfight o recuperación completa.'],
    encadena: ['zguard'], contras: [], prereq: [] },
  { id: 'zguard', nombre: 'Z guard', cat: 'bottom', familia: 'Media guardia', mecanica: 'Marco',
    pasos: ['Rodilla escudo cruzada frente a su pecho.', 'Marco de antebrazo en el cuello o bíceps.', 'Barre con el gancho profundo o entra a single X.'],
    encadena: ['singlex', 'highshield'], contras: ['Pase de presión'], prereq: ['polowka'] },
  { id: 'highshield', nombre: 'High shield', cat: 'bottom', familia: 'Media guardia', mecanica: 'Marco',
    pasos: ['Sube el escudo hasta su hombro.', 'Controla la muñeca cruzada.', 'Ataca kimura o vuelve a Z guard.'],
    encadena: ['zguard'], contras: [], prereq: ['zguard'] },
  { id: 'dlr', nombre: 'DLR (De la Riva)', cat: 'bottom', familia: 'Guardia abierta', mecanica: 'Gancho',
    pasos: ['Gancho DLR por fuera de su pierna adelantada.', 'Controla el tobillo contrario y la manga.', 'Desequilibra hacia atrás o entra al berimbolo.'],
    encadena: ['barratoplata'], contras: ['torreando'], prereq: [] },
  { id: 'inverted', nombre: 'Guardia invertida', cat: 'bottom', familia: 'Guardia abierta', mecanica: 'Rotación',
    pasos: ['Rueda sobre el hombro quedando invertido.', 'Ataca las piernas o vuelve con granby.', 'Úsala como retención ante pases laterales.'],
    encadena: ['dlr'], contras: [], prereq: ['Movilidad de cuello'] },
  { id: 'singlex', nombre: 'Single X', cat: 'bottom', familia: 'Guardia abierta', mecanica: 'Gancho',
    pasos: ['Entra bajo su pierna con tu pie en su cadera.', 'Cruza el otro gancho detrás de su rodilla.', 'Estira para barrer o transiciona a leg locks.'],
    encadena: ['straightankle'], contras: ['defensaleglockpase'], prereq: ['zguard'] },
  // Leg locks
  { id: 'straightankle', nombre: 'Straight ankle lock', cat: 'leglocks', familia: 'Ataque', mecanica: 'Tobillo',
    pasos: ['Desde single X, ajusta el pie bajo tu axila.', 'Muñeca huesuda bajo su tendón de Aquiles.', 'Arquea la cadera para finalizar.'],
    encadena: [], contras: ['defensaankle'], prereq: ['singlex'] },
  { id: 'kneebar', nombre: 'Kneebar', cat: 'leglocks', familia: 'Ataque', mecanica: 'Rodilla',
    pasos: ['Aísla la pierna con tu cadera tras su rodilla.', 'Abraza el pie contra tu pecho.', 'Extiende la cadera como un armbar de pierna.'],
    encadena: [], contras: [], prereq: [] },
  { id: 'toehold', nombre: 'Toe hold', cat: 'leglocks', familia: 'Ataque', mecanica: 'Pie',
    pasos: ['Agarre de figura cuatro sobre su empeine.', 'Lleva el pie hacia su glúteo en diagonal.'],
    encadena: ['kneebar'], contras: [], prereq: [] },
  { id: 'defensaankle', nombre: 'Defensa de straight ankle', cat: 'leglocks', familia: 'Defensa', mecanica: 'Escape',
    pasos: ['Cruza el "bota" del pie atrapado tras su cadera.', 'Alinea la rodilla y sigue su rotación.', 'Extrae la rodilla primero, el pie después.'],
    encadena: ['defensaposicion'], contras: [], prereq: [] },
  { id: 'defensaposicion', nombre: 'Posición defensiva de piernas', cat: 'leglocks', familia: 'Defensa', mecanica: 'Escape',
    pasos: ['Esconde los talones y junta las rodillas.', 'Controla la distancia con marcos en sus espinillas.', 'Recupera guardia sin ceder el ángulo.'],
    encadena: [], contras: [], prereq: [] },
]

// Nodo extra para el grafo (posición, no técnica registrable)
export const NODOS_EXTRA = [{ id: 'sidecontrol', nombre: 'Side control' }]

export const FLUJO = {
  nodos: [
    { id: 'dlr', x: 30, y: 70, w: 76 },
    { id: 'torreando', x: 140, y: 62, w: 168, activo: true },
    { id: 'retencion', x: 20, y: 180, w: 100, etiqueta: 'Retención' },
    { id: 'sidecontrol', x: 150, y: 175, w: 150, etiqueta: 'Side control' },
    { id: 'armbar', x: 70, y: 300, w: 110 },
    { id: 'kimura', x: 230, y: 300, w: 110, etiqueta: 'Kimura' },
  ],
  aristas: [
    { de: 'dlr', a: 'torreando', tipo: 'encadena' },
    { de: 'retencion', a: 'dlr', tipo: 'contra' },
    { de: 'torreando', a: 'sidecontrol', tipo: 'encadena' },
    { de: 'sidecontrol', a: 'armbar', tipo: 'encadena' },
    { de: 'sidecontrol', a: 'kimura', tipo: 'encadena' },
  ],
}

export const ACADEMIAS = [
  { id: 'atos', nombre: 'Atos Jiu-Jitsu HQ', ciudad: 'San Diego', pais: 'EE.UU.', lat: 32.7, lon: -117.2, tags: ['Gi', 'No-Gi', 'Visitantes'] },
  { id: 'aoj', nombre: 'Art of Jiu Jitsu', ciudad: 'Costa Mesa', pais: 'EE.UU.', lat: 33.6, lon: -117.9, tags: ['Gi', 'Visitantes'] },
  { id: 'marcelo', nombre: 'Marcelo Garcia NYC', ciudad: 'Nueva York', pais: 'EE.UU.', lat: 40.7, lon: -74.0, tags: ['Gi', 'No-Gi'] },
  { id: 'checkmat', nombre: 'Checkmat São Paulo', ciudad: 'São Paulo', pais: 'Brasil', lat: -23.5, lon: -46.6, tags: ['Gi', 'No-Gi'] },
  { id: 'alliance', nombre: 'Alliance São Paulo', ciudad: 'São Paulo', pais: 'Brasil', lat: -23.6, lon: -46.7, tags: ['Gi', 'Visitantes'] },
  { id: 'rogergracie', nombre: 'Roger Gracie Academy', ciudad: 'Londres', pais: 'Reino Unido', lat: 51.5, lon: -0.2, tags: ['Gi', 'Visitantes'] },
  { id: 'absolute', nombre: 'Absolute MMA', ciudad: 'Melbourne', pais: 'Australia', lat: -37.8, lon: 145.0, tags: ['No-Gi', 'Visitantes'] },
  { id: 'carpediem', nombre: 'Carpe Diem', ciudad: 'Tokio', pais: 'Japón', lat: 35.7, lon: 139.7, tags: ['Gi', 'No-Gi', 'Visitantes'] },
  { id: 'chiloe', nombre: 'Chiloé BJJ', ciudad: 'Castro', pais: 'Chile', lat: -42.5, lon: -73.8, tags: ['Gi', 'Tu academia'] },
]

export const CHECKLIST = [
  { seccion: 'DE PIE', items: [
    { id: 'singleleg', nombre: 'Single leg', estado: 2 },
    { id: 'duckunder', nombre: 'Duck under', estado: 1 },
    { id: 'uchimata', nombre: 'Uchimata', estado: 0 },
    { id: 'taiotoshi', nombre: 'Tai otoshi', estado: 2 },
    { id: 'sasae', nombre: 'Sasae', estado: 1 },
    { id: 'kataguruma', nombre: 'Kata guruma', estado: 0 },
  ]},
  { seccion: 'GUARDIA', items: [
    { id: 'scissorsweep', nombre: 'Scissor sweep', estado: 2 },
    { id: 'triangle', nombre: 'Triangle', estado: 2 },
    { id: 'armbar', nombre: 'Armbar', estado: 2 },
    { id: 'omoplata', nombre: 'Omoplata', estado: 1 },
    { id: 'barratoplata', nombre: 'Barrato plata', estado: 0 },
  ]},
  { seccion: 'BOTTOM WORK', items: [
    { id: 'zguard', nombre: 'Z guard', estado: 2 },
    { id: 'dlr', nombre: 'DLR', estado: 1 },
    { id: 'singlex', nombre: 'Single X', estado: 1 },
  ]},
  { seccion: 'LEG LOCKS', items: [
    { id: 'straightankle', nombre: 'Straight ankle', estado: 1 },
    { id: 'defensaankle', nombre: 'Defensa de straight ankle', estado: 0 },
    { id: 'defensaposicion', nombre: 'Posición defensiva', estado: 1 },
  ]},
]

export const ESTUDIANTES = [
  { id: 1, nombre: 'Camila R.', cinturon: 'azul', grado: '2°', asistencia: 4, checklist: 64, alerta: null },
  { id: 2, nombre: 'Nico P.', cinturon: 'blanco', grado: '4°', asistencia: 1, checklist: 20, alerta: '3 semanas sin entrenar' },
  { id: 3, nombre: 'Vale M.', cinturon: 'morado', grado: '—', asistencia: 3, checklist: 41, alerta: null },
  { id: 4, nombre: 'Álvaro S.', cinturon: 'blanco', grado: '1°', asistencia: 3, checklist: 18, alerta: null },
]

export const DOMINIO_INICIAL = {
  uchimata: 2, taiotoshi: 3, haraigoshi: 1, sasae: 0, ogoshi: 1, kataguruma: 0,
  singleleg: 3, duckunder: 2, armdrag: 1, scissorsweep: 3, triangle: 3, armbar: 3,
  zguard: 3, dlr: 2, singlex: 1, torreando: 2, straightankle: 1,
}
